version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "90:90"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
    networks:
      - hq-api
  mysql:
    image: mysql:8
    platform: linux/amd64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - hq-api
  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - hq-api
  composer:
    build: 
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - hq-api
  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
    networks:
      - hq-api
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - hq-api
networks:
  hq-api:
    driver: bridge
    
      