version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 433:433
  php:
    build: 
      context: .
      dockerfile: php.prod.dockerfile
      